/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import java.awt.Color;
import AppPackage.AnimationClass;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Canaima
 */
public class usuario extends javax.swing.JFrame {

    private Object color;

    /**
     * Creates new form usuario
     */
    
    Connection cc;
    
    public usuario() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(usuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void abrirInternet(){

        try {
            Desktop.getDesktop().browse(URI.create("www.google.com"));
        } catch (IOException ex) {
            Logger.getLogger(usuario.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"error");
        }

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo1 = new javax.swing.ButtonGroup();
        ingreso = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTextField2 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jmusica = new javax.swing.JLabel();
        jcalculadora = new javax.swing.JLabel();
        jinternet = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        registro = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        apellido = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        femenino = new javax.swing.JRadioButton();
        masculino = new javax.swing.JRadioButton();
        jLabel30 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        clave = new javax.swing.JPasswordField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel31 = new javax.swing.JLabel();
        fecha = new com.toedter.calendar.JDateChooser();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel34 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        correo = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel38 = new javax.swing.JLabel();
        pricipal = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ingreso.setBackground(new java.awt.Color(255, 255, 255));
        ingreso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        ingreso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 51, 0));
        jLabel1.setFont(new java.awt.Font("High Tower Text", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("USUARIO");
        ingreso.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 70, 30));

        jLabel2.setFont(new java.awt.Font("High Tower Text", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 0));
        jLabel2.setText("CLAVE");
        ingreso.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 70, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_User_96px_2.png"))); // NOI18N
        ingreso.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 100, 100));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        ingreso.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 230, 10));

        jTextField2.setForeground(new java.awt.Color(153, 153, 153));
        jTextField2.setText("INGRESE USUARIO");
        jTextField2.setBorder(null);
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField2FocusGained(evt);
            }
        });
        ingreso.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 200, 30));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        ingreso.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 230, 10));

        jPasswordField1.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.setBorder(null);
        jPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusGained(evt);
            }
        });
        ingreso.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 190, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_customer_32px_1.png"))); // NOI18N
        ingreso.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Key_32px.png"))); // NOI18N
        ingreso.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 30, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Menu_32px.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        ingreso.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Enter_OFF.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Enter_ON.png"))); // NOI18N
        jButton1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Enter_ON.png"))); // NOI18N
        jButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Enter_ON.png"))); // NOI18N
        ingreso.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 471, 110, 40));

        jmusica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Musical_Notes_32px.png"))); // NOI18N
        jmusica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmusica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmusicaMouseClicked(evt);
            }
        });
        ingreso.add(jmusica, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 140, 30, 30));

        jcalculadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Calculator_32px.png"))); // NOI18N
        jcalculadora.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jcalculadora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcalculadoraMouseClicked(evt);
            }
        });
        ingreso.add(jcalculadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 60, 30, 30));

        jinternet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Globe_32px.png"))); // NOI18N
        jinternet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jinternet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jinternetMouseClicked(evt);
            }
        });
        ingreso.add(jinternet, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 100, 30, 30));

        jLabel20.setFont(new java.awt.Font("High Tower Text", 0, 12)); // NOI18N
        jLabel20.setForeground(java.awt.Color.darkGray);
        jLabel20.setText("REGISTRO DE USUARIO");
        jLabel20.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel20MouseMoved(evt);
            }
        });
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel20MouseExited(evt);
            }
        });
        ingreso.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 530, -1, -1));

        getContentPane().add(ingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 580));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Multiply_32px.png"))); // NOI18N
        jLabel23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, -1, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Expand_Arrow_32px.png"))); // NOI18N
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 30, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 690, 50));

        registro.setBackground(new java.awt.Color(255, 255, 255));
        registro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        registro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("High Tower Text", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 51, 0));
        jLabel21.setText("REGISTRO DE USUARIO");
        registro.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        jLabel25.setFont(new java.awt.Font("High Tower Text", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 51, 0));
        jLabel25.setText("FECHA DE NACIMIENTO");
        registro.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_customer_32px_1.png"))); // NOI18N
        registro.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        nombre.setFont(new java.awt.Font("High Tower Text", 0, 14)); // NOI18N
        nombre.setForeground(new java.awt.Color(102, 102, 102));
        nombre.setText("Nombre Completo");
        nombre.setBorder(null);
        nombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nombreFocusGained(evt);
            }
        });
        registro.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 260, 30));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        registro.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 260, 10));

        jLabel26.setFont(new java.awt.Font("High Tower Text", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 51, 0));
        jLabel26.setText("APELLIDOS");
        registro.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, -1, -1));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_customer_32px_1.png"))); // NOI18N
        registro.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, -1, -1));

        apellido.setFont(new java.awt.Font("High Tower Text", 0, 14)); // NOI18N
        apellido.setForeground(new java.awt.Color(102, 102, 102));
        apellido.setText("Apellido Completo");
        apellido.setBorder(null);
        apellido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                apellidoFocusGained(evt);
            }
        });
        registro.add(apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 270, 30));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        registro.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 300, 10));

        jLabel28.setFont(new java.awt.Font("High Tower Text", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 51, 0));
        jLabel28.setText("USUARIO");
        registro.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        jLabel29.setFont(new java.awt.Font("High Tower Text", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 51, 0));
        jLabel29.setText("CLAVE");
        registro.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, -1, -1));

        femenino.setBackground(new java.awt.Color(255, 255, 255));
        grupo1.add(femenino);
        femenino.setFont(new java.awt.Font("High Tower Text", 0, 12)); // NOI18N
        femenino.setForeground(new java.awt.Color(255, 51, 0));
        femenino.setText("FEMENINO");
        femenino.setBorder(null);
        femenino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femeninoActionPerformed(evt);
            }
        });
        registro.add(femenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, -1, -1));

        masculino.setBackground(new java.awt.Color(255, 255, 255));
        grupo1.add(masculino);
        masculino.setFont(new java.awt.Font("High Tower Text", 0, 12)); // NOI18N
        masculino.setForeground(new java.awt.Color(255, 51, 0));
        masculino.setText("MASCULINO");
        masculino.setBorder(null);
        registro.add(masculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, -1, -1));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_customer_32px_1.png"))); // NOI18N
        registro.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        usuario.setFont(new java.awt.Font("High Tower Text", 0, 14)); // NOI18N
        usuario.setForeground(new java.awt.Color(102, 102, 102));
        usuario.setText("Usuario");
        usuario.setBorder(null);
        usuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usuarioFocusGained(evt);
            }
        });
        registro.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 250, 30));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        registro.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 290, 10));

        clave.setForeground(new java.awt.Color(153, 153, 153));
        clave.setText("jPasswordField2");
        clave.setBorder(null);
        clave.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                claveFocusGained(evt);
            }
        });
        registro.add(clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, 260, 30));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        registro.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 300, 10));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Key_32px.png"))); // NOI18N
        registro.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, -1, -1));

        fecha.setForeground(new java.awt.Color(255, 51, 0));
        registro.add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 230, 30));

        jLabel32.setFont(new java.awt.Font("High Tower Text", 0, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 51, 0));
        jLabel32.setText("NOMBRES");
        registro.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 127, -1, 10));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_customer_32px_1.png"))); // NOI18N
        registro.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));
        registro.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 300, 10));

        jSeparator8.setBackground(new java.awt.Color(0, 0, 0));
        registro.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 660, 10));

        jLabel34.setFont(new java.awt.Font("High Tower Text", 0, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 51, 0));
        jLabel34.setText("DATOS PERSONALES");
        registro.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jSeparator9.setBackground(new java.awt.Color(0, 0, 0));
        registro.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 312, 660, 10));

        jLabel35.setFont(new java.awt.Font("High Tower Text", 0, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 51, 0));
        jLabel35.setText("CREACION DE USUARIO");
        registro.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabel36.setFont(new java.awt.Font("High Tower Text", 0, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 51, 0));
        jLabel36.setText("CORREO ELECTRONICO");
        registro.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_customer_32px_1.png"))); // NOI18N
        registro.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));

        correo.setFont(new java.awt.Font("High Tower Text", 0, 14)); // NOI18N
        correo.setForeground(new java.awt.Color(102, 102, 102));
        correo.setText("Correo Electronico");
        correo.setBorder(null);
        correo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                correoFocusGained(evt);
            }
        });
        registro.add(correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 250, 30));

        jSeparator11.setBackground(new java.awt.Color(0, 0, 0));
        registro.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 290, 10));

        jLabel38.setFont(new java.awt.Font("High Tower Text", 1, 18)); // NOI18N
        jLabel38.setForeground(java.awt.Color.darkGray);
        jLabel38.setText("SIGUIENTE>>");
        jLabel38.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel38.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel38MouseMoved(evt);
            }
        });
        jLabel38.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel38MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel38MouseExited(evt);
            }
        });
        registro.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 460, -1, -1));

        getContentPane().add(registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 690, 530));

        pricipal.setBackground(new java.awt.Color(255, 255, 255));
        pricipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pricipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Idea_96px.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel7MouseMoved(evt);
            }
        });
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });
        pricipal.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 100, 110));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Google_Drive_96px.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel8MouseMoved(evt);
            }
        });
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });
        pricipal.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 90, 100));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Clock_96px.png"))); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel9MouseMoved(evt);
            }
        });
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
        });
        pricipal.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 90, 100));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Handshake_96px.png"))); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel10MouseMoved(evt);
            }
        });
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel10MouseExited(evt);
            }
        });
        pricipal.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 100, 100));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Maintenance_96px.png"))); // NOI18N
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel11MouseMoved(evt);
            }
        });
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel11MouseExited(evt);
            }
        });
        pricipal.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, -1, 110));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Today_96px.png"))); // NOI18N
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel12MouseMoved(evt);
            }
        });
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel12MouseExited(evt);
            }
        });
        pricipal.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 320, 90, 100));

        jLabel13.setFont(new java.awt.Font("High Tower Text", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setText("PROGRAMADO");
        pricipal.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 440, -1, 20));

        jLabel14.setFont(new java.awt.Font("High Tower Text", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setText("DRIVER");
        pricipal.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, 20));

        jLabel15.setFont(new java.awt.Font("High Tower Text", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setText("RELOJ");
        pricipal.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, -1, 20));

        jLabel16.setFont(new java.awt.Font("High Tower Text", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setText("SOCIO");
        pricipal.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, -1, 20));

        jLabel17.setFont(new java.awt.Font("High Tower Text", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 0, 0));
        jLabel17.setText("IDEA");
        pricipal.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, -1, 20));

        jLabel18.setFont(new java.awt.Font("High Tower Text", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 0, 0));
        jLabel18.setText("MANTENIMINETO");
        pricipal.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, -1, 20));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Search_32px_2.png"))); // NOI18N
        pricipal.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        jTextField1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 102, 0), new java.awt.Color(255, 102, 0), new java.awt.Color(255, 102, 0), new java.awt.Color(255, 102, 0)));
        pricipal.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 340, 30));

        getContentPane().add(pricipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 800, 690, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        
        AnimationClass internet = new AnimationClass();
        internet.jLabelXRight(-40, 10, 10, 5, jinternet);
        
        AnimationClass calculadora = new AnimationClass();
        calculadora.jLabelXRight(-40, 10, 10, 5, jcalculadora);
        
        AnimationClass musica = new AnimationClass();
        musica.jLabelXRight(-40, 10, 10, 5, jmusica);
        
        //<---
        
        AnimationClass internet2 = new AnimationClass();
        internet2.jLabelXLeft(10, -40, 10, 5, jinternet);
        
        AnimationClass calculadora2 = new AnimationClass();
        calculadora2.jLabelXLeft(10, -40, 10, 5, jcalculadora);
        
        AnimationClass musica2 = new AnimationClass();
        musica2.jLabelXLeft(10, -40, 10, 5, jmusica);
        
    }//GEN-LAST:event_jLabel6MouseClicked
    
    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        
        System.exit(0);
    }//GEN-LAST:event_jLabel23MouseClicked
    
    private void jLabel8MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseMoved
        
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(Color.gray));
    }//GEN-LAST:event_jLabel8MouseMoved
    
    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
        
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(Color.white));
    }//GEN-LAST:event_jLabel8MouseExited
    
    private void jLabel9MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseMoved
        
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(Color.gray));
    }//GEN-LAST:event_jLabel9MouseMoved
    
    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
        
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(Color.white));
    }//GEN-LAST:event_jLabel9MouseExited
    
    private void jLabel10MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseMoved
        
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(Color.gray));
    }//GEN-LAST:event_jLabel10MouseMoved
    
    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited
        
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(Color.white));
    }//GEN-LAST:event_jLabel10MouseExited
    
    private void jLabel7MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseMoved
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(Color.gray));
    }//GEN-LAST:event_jLabel7MouseMoved
    
    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(Color.white));
    }//GEN-LAST:event_jLabel7MouseExited
    
    private void jLabel11MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseMoved
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(Color.gray));
    }//GEN-LAST:event_jLabel11MouseMoved
    
    private void jLabel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseExited
        
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(Color.white));
    }//GEN-LAST:event_jLabel11MouseExited
    
    private void jLabel12MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseMoved
        
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(Color.gray));        
    }//GEN-LAST:event_jLabel12MouseMoved
    
    private void jLabel12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseExited
        
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(Color.white));
    }//GEN-LAST:event_jLabel12MouseExited

    private void femeninoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femeninoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femeninoActionPerformed

    private void jLabel20MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseMoved
     
        jLabel20.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jLabel20MouseMoved

    private void jLabel20MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseExited
    
        jLabel20.setForeground(Color.DARK_GRAY);
    }//GEN-LAST:event_jLabel20MouseExited

    private void jmusicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmusicaMouseClicked
    
        try {
            Runtime rt =Runtime.getRuntime();
            Process p = rt.exec("música.lnk");
            try {
                p.waitFor();
            } catch (InterruptedException ex) {
                Logger.getLogger(usuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (IOException ex) {
            Logger.getLogger(usuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jmusicaMouseClicked

    private void jcalculadoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcalculadoraMouseClicked
    
        try {
            Runtime rt = Runtime.getRuntime();
            Process p = rt.exec("calc");
            try {
                p.waitFor();
            } catch (InterruptedException ex) {
                Logger.getLogger(usuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (IOException ex) {
            Logger.getLogger(usuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jcalculadoraMouseClicked

    private void jinternetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jinternetMouseClicked
     
        try {
            Desktop.getDesktop().browse(URI.create("www.google.com"));
        } catch (IOException ex) {
            Logger.getLogger(usuario.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"error");
        }
    }//GEN-LAST:event_jinternetMouseClicked

    private void jLabel38MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel38MouseMoved
    
        jLabel38.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jLabel38MouseMoved

    private void jLabel38MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel38MouseExited
    
        jLabel38.setForeground(Color.DARK_GRAY);
        
    }//GEN-LAST:event_jLabel38MouseExited

    private void jLabel38MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel38MouseClicked

        String clv=String.valueOf(clave.getPassword());
        
        int ano= fecha.getCalendar().get(Calendar.YEAR);
        int mes= fecha.getCalendar().get(Calendar.MONTH);
        int dia= fecha.getCalendar().get(Calendar.DAY_OF_MONTH);
        
        String nacimiento=""+ano+"-"+mes+"-"+dia;
        
        String sexo="";
        
        if(masculino.isSelected()){
        
            sexo="M";
        
        }
        if(femenino.isSelected()){
        
            sexo="F";
        
        }
        
        if(nombre.getText().isEmpty() || apellido.getText().isEmpty() || usuario.getText().isEmpty() ||clv.isEmpty() ){
        
            JOptionPane.showMessageDialog(null,"rellene los espacios requeridos");
        
        }
        else{
        
        
            try {
                cc=DriverManager.getConnection("jdbc:mysql://localhost/pratica","root","");
                Statement stmt= cc.createStatement();
                stmt.executeUpdate("INSERT INTO usuario VALUES('0','"+nombre.getText()+"','"+apellido.getText()+"','"+usuario.getText()+"','"+clv+"','"+correo.getText()+"','"+nacimiento+"','"+sexo+"')");
                JOptionPane.showMessageDialog(null,"registro completo");
            } catch (SQLException ex) {
                Logger.getLogger(usuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }
        
        
    }//GEN-LAST:event_jLabel38MouseClicked

    private void jTextField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusGained
       
        jTextField2.setText("");
    }//GEN-LAST:event_jTextField2FocusGained

    private void jPasswordField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusGained

        jPasswordField1.setText("");
    }//GEN-LAST:event_jPasswordField1FocusGained

    private void nombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreFocusGained
    
        nombre.setText("");
    }//GEN-LAST:event_nombreFocusGained

    private void apellidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_apellidoFocusGained
    
        apellido.setText("");
    }//GEN-LAST:event_apellidoFocusGained

    private void usuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usuarioFocusGained
        
        usuario.setText("");
    }//GEN-LAST:event_usuarioFocusGained

    private void claveFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_claveFocusGained
    
        clave.setText("");
    }//GEN-LAST:event_claveFocusGained

    private void correoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_correoFocusGained
    
       correo.setText("");
    }//GEN-LAST:event_correoFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new usuario().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellido;
    private javax.swing.JPasswordField clave;
    private javax.swing.JTextField correo;
    private com.toedter.calendar.JDateChooser fecha;
    private javax.swing.JRadioButton femenino;
    private javax.swing.ButtonGroup grupo1;
    private javax.swing.JPanel ingreso;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel jcalculadora;
    private javax.swing.JLabel jinternet;
    private javax.swing.JLabel jmusica;
    private javax.swing.JRadioButton masculino;
    private javax.swing.JTextField nombre;
    private javax.swing.JPanel pricipal;
    private javax.swing.JPanel registro;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
